<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon />
    <RootNamespace>FlickrSlideshow.XboxTest</RootNamespace>
    <AssemblyName>FlickrSlideshow.XboxTest</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlickrSlideshow.Core\FlickrSlideshow.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
